name: Push to main branch
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release Main Branch
    runs-on: ubuntu-latest
    environment: alpha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Create .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc
      - name: Create env file
        run: |
          touch .env.production
          echo RELEASE=alpha
          echo POSTHOG_KEY=${{ secrets.POSTHOG_DEV_KEY }} >> .env.production
          echo COVALENT_API_KEY=${{ secrets.COVALENT_API_KEY }} >> .env.production
          echo GLACIER_URL=${{ secrets.GLACIER_URL }} >> .env.production
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env.production
      - name: Install dependencies
        run: yarn setup
      - name: Build library
        run: yarn build:alpha
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCH: main
        run: yarn run semantic-release
      - name: Changelog
        run: yarn changelog
      - name: Stage Version Updates
        run: git add .
      - name: Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(version): update package.json version and changelog'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: chore/version-update
          delete-branch: true
          title: '[CI/CD] Update version and create changelog if applicable'
          draft: false
