name: Push to release branch

on:
  push:
    branches:
      - test-beta
jobs:
  release:
    uses: ava-labs/extension-avalanche/.github/workflows/release.yaml
  rebase:
    - name: rebase main
      runs-on: ubuntu-latest
      run: |
        git checkout test-alpha
        git rebase test-beta
        git push origin head
