name: Push to release branch

on:
  push:
    branches:
      - test-beta
jobs:
  release:
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: build and release
        uses: ./.github/workflows/release.yaml
      - name: rebase main
        run: |
          git checkout test-alpha
          git rebase test-beta
          git push origin head
