name: Push to release branch

on:
  push:
    branches:
      - test-beta
jobs:
  release:
    uses: ava-labs/extension-avalanche/.github/workflows/release.yaml@test-beta
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: rebase main
        run: |
          git checkout test-alpha
          git rebase test-beta
          git push origin head
