name: PR checks
on: pull_request
jobs:
  lint:
    name: Lint and build
    runs-on: ubuntu-latest
    environment: alpha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Create .npmrc
        run: echo '//registry.npmjs.org/:_authToken= ${{ secrets.NPM_TOKEN }}' >> .npmrc
      - name: Create env file
        run: |
          touch .env.production
          echo POSTHOG_KEY=${{ secrets.POSTHOG_KEY }} >> .env.production
          echo GLACIER_URL=${{ secrets.GLACIER_URL }} >> .env.production
      - name: Install dependencies
        run: yarn setup
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build extension
        run: yarn build
