name: PR checks
on: pull_request
jobs:
  lint:
    name: Lint and build
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Create .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build extension
        run: yarn build
