name: PR checks
on: pull_request
jobs:
  lint:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Create .npmrc with NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - name: Install dependencies
        run: yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint
        run: yarn lint
      - name: Build extension
        run: yarn build:ci
