name: PR checks
on: pull_request
jobs:
  lint:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build extension
        run: yarn build:ci
