name: Push to release branch

on:
  push:
    branches:
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Create .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - name: Install dependencies
        run: yarn
      - name: Build library
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCH: release
        run: yarn run semantic-release
  rebase:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: rebase main
        run: |
          git checkout main &&
          git rebase release &&
          git push origin main
